version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    working_dir:
      /var/opt/app
    volumes:
      - ./app:/var/opt/app
      - node_modules_volume:/var/opt/app/node_modules
    command: ['yarn', 'run', 'dev']
    tty: true
    stdin_open: true

volumes:
  node_modules_volume:
